---
version: "2"
services:
    traefik:
        container_name: traefik
        image: "traefik:v2.2"
        restart: unless-stopped
        command:
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--api.insecure" # Don't do that in production
            - "--serversTransport.insecureSkipVerify=true"
            - "--providers.docker=true"
            - "--certificatesresolvers.default_httpchallenge.acme.httpchallenge=true"
            - "--certificatesresolvers.default_httpchallenge.acme.httpchallenge.entrypoint=web"
            - "--certificatesresolvers.default_httpchallenge.acme.email=Cole@Greenlee.io"
            - "--certificatesresolvers.default_httpchallenge.acme.storage=/letsencrypt/acme.json"
        labels:
            - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
            - "traefik.http.routers.http-catchall.entrypoints=web"
            - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        ports:
            - "443:443"
            - "80:80"
            - "8888:8080"
        volumes:
            - "./letsencrypt:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx/html:/usr/share/nginx/html
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nginx.rule=Host(\"greenlee.io\")"
            - "traefik.http.routers.nginx.entrypoints=websecure"
            - "traefik.http.routers.nginx.tls.certresolver=default_httpchallenge"
            - "traefik.http.services.nginx.loadbalancer.server.port=80"
    unifi-controller:
        image: linuxserver/unifi-controller
        container_name: unifi-controller
        restart: always
        environment:
            - PUID=1000
            - PGID=1000
            - MEM_LIMIT=1024M
        volumes:
            - ./unifi/config:/config
        ports:
            - 3478:3478/udp
            - 10001:10001/udp
            - 8080:8080
            - 8081:8081
            - 8443:8443
            - 8843:8843
            - 8880:8880
            - 6789:6789
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.unifi.rule=Host(\"unifi.greenlee.io\")"
            - "traefik.http.routers.unifi.entrypoints=websecure"
            - "traefik.http.routers.unifi.tls.certresolver=default_httpchallenge"
            - "traefik.http.services.unifi.loadbalancer.server.port=8443"
            - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
