version: '3'
services:
    subspace:
        restart: always
        labels:
            - "traefik.enable=true"
            - traefik.backend=subspace
            - traefik.port=443
            - "traefik.frontend.rule=Host:vpn.greenlee.io"
        volumes:
            - '/usr/bin/wg:/usr/bin/wg'
            - './data:/data'
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        cap_add:
            - NET_ADMIN
        environment:
            - SUBSPACE_HTTP_HOST=vpn.greenlee.io
        image: 'subspacecloud/subspace:latest'
