---
version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ${CONFIG_PATH}:/config
      - ${MEDIA_PATH}/tv:/data/tv
      - ${MEDIA_PATH}/tv:/data/movies
      - ${MEDIA_PATH}/anime:/data/anime
      - ${TRANSCODE_PATH}:/transcode
    restart: unless-stopped