version: "3"
services:
  ombi:
    image: linuxserver/ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./config:/config
#    ports:
#      - 3579:3579
    expose:
      - 3579
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ombi"
      - "traefik.frontend.rule=Host:ombi.greenlee.io"
      - "traefik.port=3579"

