---
version: '3'

services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "8443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      ServerIP: 192.168.1.2
    labels:
      - "traefik.enable=true"
      - traefik.backend=pihole
      - traefik.port=80
      - "traefik.frontend.rule=Host:pihole.thenet.lan"
    volumes:
      - ./pihole/:/etc/pihole/
      - ./pihole/dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
  jenkins:
    ports:
        - '49001:8080'
      volumes:
          - './jenkins:/var/jenkins_home:z'
      image: run
  netbootxyz:
    image: linuxserver/netbootxyz
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - MENU_VERSION=
    volumes:
      - ./netbootxyz/config:/config
      - /netbootxyz/assets:/assets
    ports:
      - 3000:3000
      - 69:69/udp
      # - 8080:80 #optional
    restart: unless-stopped