---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022
    volumes:
      - ./sonarr/config:/config
      - ${MEDIA_PATH}/Anime:/anime
      - ${MEDIA_PATH}/TV:/tv
      - ${MEDIA_PATH}/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022
    volumes:
      - ./radarr/config:/config
      - ${MEDIA_PATH}/Movies:/movies
      - ${MEDIA_PATH}/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - BASE_URL=/ombi
    volumes:
      - ./ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ${MEDIA_PATH}/Downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
  nzbget:
    image: linuxserver/nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./nzbget/config:/config
      - ${MEDIA_PATH}/Downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

  hydra2:
    image: linuxserver/hydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./hydra/config:/config
      - ${MEDIA_PATH}/Downloads:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped
