version: "2"
services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
#      - PASSWORD=password #optional
#      - SUDO_PASSWORD=password #optional
    volumes:
      - ./config:/config
    ports:
      - 9443:8443
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=code-server"
      - "traefik.frontend.rule=Host:code.greenlee.io"
      - "traefik.port=9443"
