---
version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./plex/config:/config
      - ${MEDIA_PATH}/tv:/data/tv
      - ${MEDIA_PATH}/movies:/data/movies
      - ${MEDIA_PATH}/anime:/data/anime
      - ${MEDIA_PATH}/transcode:/transcode
    restart: unless-stopped
  tinymediamanager_service:
    image: romancin/tinymediamanager:latest
    container_name: tinymediamanager
    ports:
      - "5803:5800"
    environment:
      - USER_ID=0
      - GROUP_ID=0
      - TZ=America/Chicago
      - VNC_PASSWORD=${TINY_MEDIA_MANAGER_WEBUI_PASSWORD}
    volumes:
      - "./tinymediamanager/config:/config:rw"
      - "${MEDIA_PATH}:/media:rw"