---
version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ${CONFIG_PATH}:/config
      - ${MEDIA_PATH}/tv:/data/tv
      - ${MEDIA_PATH}/movies:/data/movies
      - ${MEDIA_PATH}/anime:/data/anime
      - ${TRANSCODE_PATH}:/transcode
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022
    volumes:
      - ./config:/config
      - ${MEDIA_STORAGE_PATH}:/tv
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022
    volumes:
      - ./config:/config
      - ${MEDIA_STORAGE_PATH}:/movies
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./config:/config
#    ports:
#      - 3579:3579
    expose:
      - 3579
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ombi"
      - "traefik.frontend.rule=Host:ombi.greenlee.io"
      - "traefik.port=3579"


