version: "2"
services:
  radarr:
    image: linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022
    volumes:
      - ./config:/config
      - ${MEDIA_STORAGE_PATH}:/movies
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
