all:
  children:
    vps:
      hosts:
        greenlee.io:
          ansible_user: cole
        colegreenlee.com:
          ansible_user: cole
    servers:
      hosts:
        v.greenlee.io:
          ansible_user: cole
          ansible_port: 420
